import { Product, WoodProduct, Customer, Supplier, Sale, User } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Kamau',
    email: 'john@mayondo.com',
    role: 'manager',
  },
  {
    id: '2',
    name: 'Mary Wanjiru',
    email: 'mary@mayondo.com',
    role: 'attendant',
  },
  {
    id: '3',
    name: 'Peter Ochieng',
    email: 'peter@mayondo.com',
    role: 'attendant',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Royal Oak King Bed',
    type: 'bed',
    price: 85000,
    costPrice: 65000,
    images: ['/api/placeholder/400/300'],
    measurements: {
      width: '180cm',
      height: '120cm',
      depth: '200cm',
    },
    color: 'Dark Walnut',
    quality: 'premium',
    stockQuantity: 5,
    supplier: 'Timber Masters Ltd',
    description: 'Luxurious king-size bed crafted from premium oak wood',
    featured: true,
  },
  {
    id: '2',
    name: 'Modern L-Shape Sofa',
    type: 'sofa',
    price: 125000,
    costPrice: 95000,
    images: ['/api/placeholder/400/300'],
    measurements: {
      width: '280cm',
      height: '85cm',
      depth: '180cm',
    },
    color: 'Charcoal Grey',
    quality: 'premium',
    stockQuantity: 3,
    supplier: 'Comfort Furnishings',
    description: 'Contemporary L-shaped sofa with premium upholstery',
    featured: true,
  },
  {
    id: '3',
    name: 'Mahogany Dining Table',
    type: 'table',
    price: 68000,
    costPrice: 50000,
    images: ['/api/placeholder/400/300'],
    measurements: {
      width: '180cm',
      height: '75cm',
      depth: '90cm',
    },
    color: 'Natural Mahogany',
    quality: 'premium',
    stockQuantity: 8,
    supplier: 'Timber Masters Ltd',
    description: '6-seater dining table made from solid mahogany',
  },
  {
    id: '4',
    name: 'Classic Wardrobe',
    type: 'wardrobe',
    price: 45000,
    costPrice: 32000,
    images: ['/api/placeholder/400/300'],
    measurements: {
      width: '120cm',
      height: '200cm',
      depth: '60cm',
    },
    color: 'Light Oak',
    quality: 'standard',
    stockQuantity: 12,
    supplier: 'Wood Crafters',
    description: 'Spacious wardrobe with mirror and multiple compartments',
  },
  {
    id: '5',
    name: 'Executive Office Chair',
    type: 'chair',
    price: 18500,
    costPrice: 14000,
    images: ['/api/placeholder/400/300'],
    measurements: {
      width: '65cm',
      height: '120cm',
      depth: '70cm',
    },
    color: 'Black Leather',
    quality: 'premium',
    stockQuantity: 15,
    supplier: 'Office Solutions',
    description: 'Ergonomic executive chair with genuine leather',
  },
  {
    id: '6',
    name: 'Kitchen Cabinet Set',
    type: 'cupboard',
    price: 95000,
    costPrice: 70000,
    images: ['/api/placeholder/400/300'],
    measurements: {
      width: '300cm',
      height: '90cm',
      depth: '60cm',
    },
    color: 'White & Wood',
    quality: 'standard',
    stockQuantity: 2,
    supplier: 'Kitchen Masters',
    description: 'Complete kitchen cabinet set with modern finish',
  },
];

export const woodProducts: WoodProduct[] = [
  {
    id: 'w1',
    name: 'Mahogany Timber',
    type: 'hardwood',
    supplier: 'Timber Masters Ltd',
    costPrice: 2500,
    sellingPrice: 3500,
    stockQuantity: 500,
    unit: 'per foot',
    dateReceived: '2024-01-15',
    description: 'Premium quality mahogany timber',
  },
  {
    id: 'w2',
    name: 'Pine Poles',
    type: 'poles',
    supplier: 'Wood Suppliers Co',
    costPrice: 800,
    sellingPrice: 1200,
    stockQuantity: 200,
    unit: 'per piece',
    dateReceived: '2024-01-20',
    description: 'Treated pine poles for construction',
  },
  {
    id: 'w3',
    name: 'Oak Timber',
    type: 'hardwood',
    supplier: 'Premium Woods',
    costPrice: 3000,
    sellingPrice: 4200,
    stockQuantity: 300,
    unit: 'per foot',
    dateReceived: '2024-01-18',
    description: 'High-quality oak timber',
  },
  {
    id: 'w4',
    name: 'Cedar Planks',
    type: 'softwood',
    supplier: 'Cedar Works',
    costPrice: 1800,
    sellingPrice: 2500,
    stockQuantity: 150,
    unit: 'per plank',
    dateReceived: '2024-01-22',
    description: 'Aromatic cedar planks',
  },
  {
    id: 'w5',
    name: 'Eucalyptus Poles',
    type: 'poles',
    supplier: 'Uganda Timber Co.',
    costPrice: 15000,
    sellingPrice: 25000,
    stockQuantity: 8,
    unit: 'pieces',
    dateReceived: '2024-01-20',
  },
  {
    id: 'w6',
    name: 'Teak Hardwood',
    type: 'hardwood',
    supplier: 'Forest Products Ltd',
    costPrice: 95000,
    sellingPrice: 140000,
    stockQuantity: 0,
    unit: 'cubic meters',
    dateReceived: '2024-01-18',
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'James Mwangi',
    phone: '+254 712 345 678',
    email: 'james@email.com',
    address: 'Westlands, Nairobi',
    totalPurchases: 285000,
    lastPurchase: '2024-01-25',
  },
  {
    id: 'c2',
    name: 'Grace Njeri',
    phone: '+254 722 987 654',
    email: 'grace@email.com',
    address: 'Kilimani, Nairobi',
    totalPurchases: 450000,
    lastPurchase: '2024-01-24',
  },
  {
    id: 'c3',
    name: 'David Omondi',
    phone: '+254 733 456 789',
    address: 'Lavington, Nairobi',
    totalPurchases: 180000,
    lastPurchase: '2024-01-20',
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: 's1',
    name: 'Timber Masters Ltd',
    contact: '+254 700 111 222',
    email: 'info@timbermasters.co.ke',
    address: 'Industrial Area, Nairobi',
    products: ['Mahogany', 'Oak', 'Teak'],
    rating: 4.5,
  },
  {
    id: 's2',
    name: 'Wood Suppliers Co',
    contact: '+254 700 333 444',
    email: 'sales@woodsuppliers.co.ke',
    address: 'Mombasa Road, Nairobi',
    products: ['Pine', 'Cedar', 'Cypress'],
    rating: 4.2,
  },
  {
    id: 's3',
    name: 'Comfort Furnishings',
    contact: '+254 700 555 666',
    email: 'info@comfortfurnishings.co.ke',
    address: 'Ngong Road, Nairobi',
    products: ['Sofas', 'Chairs', 'Cushions'],
    rating: 4.8,
  },
];

export const mockSales: Sale[] = [
  {
    id: 'sale1',
    customerId: 'c1',
    customerName: 'James Mwangi',
    products: [
      {
        productId: '1',
        productName: 'Royal Oak King Bed',
        quantity: 1,
        unitPrice: 85000,
        total: 85000,
      },
    ],
    subtotal: 85000,
    transportSurcharge: 4250,
    total: 89250,
    paymentType: 'cash',
    date: '2024-01-25',
    attendantId: '2',
    attendantName: 'Mary Wanjiru',
    status: 'completed',
  },
  {
    id: 'sale2',
    customerId: 'c2',
    customerName: 'Grace Njeri',
    products: [
      {
        productId: '2',
        productName: 'Modern L-Shape Sofa',
        quantity: 1,
        unitPrice: 125000,
        total: 125000,
      },
      {
        productId: '5',
        productName: 'Executive Office Chair',
        quantity: 2,
        unitPrice: 18500,
        total: 37000,
      },
    ],
    subtotal: 162000,
    transportSurcharge: 8100,
    total: 170100,
    paymentType: 'cheque',
    date: '2024-01-24',
    attendantId: '3',
    attendantName: 'Peter Ochieng',
    status: 'completed',
  },
];